### ISSUE TITLE
Problems compiling with GCC 6.1

### ISSUE THREAD

**Issue by javiergarcia** [arcosuc3m/grppi#1]
/home/fjblas/grppi/tests/pipeline+farm.cpp:100:5:   required from here
/home/software/gcc-6.1/include/c++/6.1.0/bits/stl_pair.h:224:17: internal compiler error: in cp_genericize, at cp/cp-gimplify.c:1567
       constexpr pair(const pair&) = default;
                 ^~~~
0x6e8e9d cp_genericize(tree_node*)
	../.././gcc/cp/cp-gimplify.c:1567
0x5f26f9 finish_function(int)
	../.././gcc/cp/decl.c:14820
0x69d77e synthesize_method(tree_node*)
	../.././gcc/cp/method.c:817
0x63d0c0 mark_used(tree_node*, int)
	../.././gcc/cp/decl2.c:5251
0x5d3d3a build_over_call
	../.././gcc/cp/call.c:7608
0x5d255f build_new_method_call_1
	../.././gcc/cp/call.c:8419
0x5d255f build_new_method_call(tree_node*, tree_node*, vec<tree_node*, va_gc, vl_embed>**, tree_node*, int, tree_node**, int)
	../.././gcc/cp/call.c:8489
0x69e34e locate_fn_flags
	../.././gcc/cp/method.c:900
0x69e516 get_copy_ctor(tree_node*, int)
	../.././gcc/cp/method.c:958
0x6e578b omp_cxx_notice_variable
	../.././gcc/cp/cp-gimplify.c:908
0x6e7034 cp_genericize_r
	../.././gcc/cp/cp-gimplify.c:1018

**Comment by javiergarcia** [comment]
I found that GCC 6.1 has this bug:

https://github.com/USCiLab/cereal/issues/295

Using GCC 5 works perfectly.

I suggest to close the issue.

**Comment by jdgarciauc3m** [comment]
Closed as this is not an issue.
