### ISSUE TITLE
Revise the set of overloads for reduce

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#117]
Current set of overloads includes returning the result or updating a reference.

We need to find the minimum best overload set.

**Comment by Drioastorga** [comment]
This has been modified in issue-121 branch. I think this has been solved since now only exists an interface returning the result.

**Comment by jdgarciauc3m** [comment]
Reopen until it is merged.

**Comment by jdgarciauc3m** [comment]
This was solved by PR #149
