### ISSUE TITLE
Constructor interface for mpmpc_queue

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#118]
The constructor interface for mpmc_queue is confusing.

Specifically, the fact that there is a global constant for the defult_size.

This needs further discussion.

**Comment by Drioastorga** [comment]
This issue is solved with the modifications performed for issues 85 and 114.

Specifically, the global default_size variable has been removed (issue #85) and the constructor has been modified (issue #114).

**Comment by jdgarciauc3m** [comment]
I am reopening this issue:

The constructor should not have a default mode, so that clients need to explicitly state the mode.

**Comment by jdgarciauc3m** [comment]
This is PR #157
