### ISSUE TITLE
Avoid explicit mention to incclude directories in source path

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#12]
It is strange to have things like

~~~c++
#include "include/common/common.h"
~~~

This cane be removed if we add the following to global CMake

~~~CMake
include_directories("${CMAKE_SOURCE_DIR}/include")
~~~

**Comment by Drioastorga** [comment]
The CMake have been modified in order to avoid explicit mention to the include directory in source paths.
