### ISSUE TITLE
Revise stream_reduce()

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#127]
Does it make sens the function not returning anything?

Instead of taking result by reference, return it.

**Comment by Drioastorga** [comment]
I am not sure if the versions that reduces the stream into a single value make sense. More discussion about these interfaces is needed.

**Comment by jdgarciauc3m** [comment]
I'm inclined to remove the version that reduces a whole stream.

**Comment by jdgarciauc3m** [comment]
Solved by pr #174
