### ISSUE TITLE
Revise CMake code related with TBB

### ISSUE THREAD

**Issue by Drioastorga** [arcosuc3m/grppi#132]
In the current version, TBB is enabled by default, and thus, producing an error on the CMake when it is not installed. The CMake should check if TBB is installed and then enable the TBB implementacion, otherwise it should be disabled as it is not a requirement.

**Comment by jdgarciauc3m** [comment]
Probablye we should make it enabled by default if and only if TBB is found.

**Comment by jdgarciauc3m** [comment]
Solved by PR #140
