### ISSUE TITLE
Revise GoogleTest in the CMake

### ISSUE THREAD

**Issue by Drioastorga** [arcosuc3m/grppi#175]
The CMake is not able to find the google test library and always download the current supported version from the github repository. Additionally, the CMake does not compile the dowloaded google test version and keep looking for the google test installed in the system. Therefore, the current version always fails if google test is not installed in the system.

I propose two different solutions:

1. Prefer the use of the goolge test available in the system.
In this case, the Cmake should take the following actions:
- If the supported version of google test is already installed in the system, it should link with it instead of download it in the build directory.
- Otherwise, it should clone the google test repository, compile the google test sources and link with it .

2. Compile and use the downloaded version.

**Comment by jdgarciauc3m** [comment]
This needs to be addressed by proper documentation on how to build.

We need to develop build instructions.

**Comment by jdgarciauc3m** [comment]
Solved by PR #254
