### ISSUE TITLE
Use auto return type

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#198]
Patterns retunring a complicated return type may be simplified by using an auto return type

Examples:

* map
* map/reduce
* ...

**Comment by Drioastorga** [comment]
I think that these changes have been addressed in other pull requests. I think that the only pattern that uses these metaprogrammig tricks to deduce the return type is the divide_and_conquer since the compiler is not able to deduce it due to the recursion.

**Comment by jdgarciauc3m** [comment]
OK. Solved.
