### ISSUE TITLE
Change naming convention

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#2]
We need to change the naming of the library interface to avoid CamelCase.

See: http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rl-camel

Functions should have names like:
- pipeline()
- divide_and_conquer()
- ...

**Comment by Drioastorga** [comment]
I have changed the functions names format from CamelCase to snake case.

**Comment by jdgarciauc3m** [comment]
Mostly done. Some issue might show up during code review.
