### ISSUE TITLE
Reduce with very small sizes failes for parallel_native

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#201]
If the number of elements in the sequence is very small, results are incorrect

The problem is the computation of elemeperthr that might be 0. For example an array o 3 elements of 4 threads.

We need to:
1. Add such case to unit tests
1. Modify reduction for native to take this into account.

**Comment by Drioastorga** [comment]
I think that it was solved in a previous pull request.

**Comment by jdgarciauc3m** [comment]
Solved by PR #203
