### ISSUE TITLE
Install dirs in cmake

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#21]
When I do maake install there are a number of issues:

* Old dependency from fastflow. It tries to install fastflow files.
* Include files are installed in /usr/local/GrPPI/include. The correct place would be /usr/local/include/grppi

**Comment by AndresSanchezCuadrado** [comment]
Removed fastflow installation attempt.
Modified the installation path to "include/grppi".
The project name in CMake has been renamed from "GrPPI" to "grppi".

By default the installation folder is /home/lab1/include/grppi.
With cmake .. -DCMAKE_INSTALL_PREFIX=path/to/folder it will install the files in path/to/folder/include/grppi
