### ISSUE TITLE
Doxygen configuration

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#22]
Doxygen configuration directory should named "doxy".

Generated files should be sent to directory "doc".

A README.md in the "doxy" directory should describe the contents of the directory.

What is the difference between "Doxyfile" and "Doxyfile.out". Should "Doxyfile.out" be under git?

**Comment by AndresSanchezCuadrado** [comment]
Changed the name of the docs folder to doxy.
Changed the output directory name to doc.
Created README.md file.
Changed the CMakeLists.txt file to use the Doxyfile as input and not generate the Doxyfile.out file.
