### ISSUE TITLE
Rename stream_filter to discard/keep

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#240]
Stream prefix does not add info. If we want all stream patterns to be prefixed by stream. Should we do the same with pipeline?

**Comment by jdgarciauc3m** [comment]
After discussin with @Drioastorga we decided:

* The pattern keeps the name **stream filter**
* The API changes name to function `grppi::stream_if`

**Comment by mdolz** [comment]
What does it mean `grppi::stream_if`? Wouldn't it be `grppi::filter_if`?

**Comment by jdgarciauc3m** [comment]
You are completely right.

~~~c++
grppi::filter_if
~~~

**Comment by jdgarciauc3m** [comment]
We have decided to provide two interfaces:

~~~
grppi::discard()
grppi::keep()
~~~

**Comment by jdgarciauc3m** [comment]
Solved by PR #262
