### ISSUE TITLE
Change unit tests guards

### ISSUE THREAD

**Issue by AndresSanchezCuadrado** [arcosuc3m/grppi#29]
The unitary tests used the removed file "enable_flags" to enable the different policies tests.

The unitary tests files shall be modified to change the current guards TBB_ENABLE by  GRPPI_TBB and OMP_ENABLE by GRPPI_OMP.

**Comment by jdgarciauc3m** [comment]
Use branch issue-29 for this.

**Comment by AndresSanchezCuadrado** [comment]
I have found a problem, the google tests are not working properly with openmp. 
I'm looking for the problem.

**Comment by jdgarciauc3m** [comment]
This is now solved
