### ISSUE TITLE
Unit test for farm of pipelines

### ISSUE THREAD

**Issue by Drioastorga** [arcosuc3m/grppi#305]
Add unit test for farm of pipelines

**Comment by jdgarciauc3m** [comment]
Please answer here identifying if this has been solved and how

**Comment by Drioastorga** [comment]
Unit test for farm of pipelines is already in master branch: "unit_test/farm_pipeline_composition.cpp".

**Comment by jdgarciauc3m** [comment]
Ok. Double checked. Closing issue.
