### ISSUE TITLE
OMP executor do not execute if threads number is smaller than stages

### ISSUE THREAD

**Issue by javiergarcia** [arcosuc3m/grppi#318]
The OpenMP executor does not work correctly with a smaller number of threads than executors.

**Comment by jdgarciauc3m** [comment]
Please clarify.

Which patter? Which concurrency_degree? What was the expected result?

The best way would be providing a test case. Alternatively provide a better description.

**Comment by jdgarciauc3m** [comment]
The issue is that gcc (at least version 6) does not implement a valid `taskyield()`.

Proposed resolution now would be to issue an error message if number of required tasks of a pipeline exceeds the concurrency degree.

**Comment by jdgarciauc3m** [comment]
This is a known issue with OpenMP under gcc. We added a note in the documentation of parallel_execution_omp.

If the issue happens with clang or intel, please reopen the issue.
