### ISSUE TITLE
Compiling Error Redefinition of Default Template Parameter

### ISSUE THREAD

**Issue by tete17** [arcosuc3m/grppi#320]
I am getting some errors trying to compile the unit tests and the tests with clang-3.8.0 . It seems there is some redefinition of default parameters in 
![captura de pantalla de 2018-02-15 01-28-19](https://user-images.githubusercontent.com/13263011/36235204-87db1bf0-11ef-11e8-8bb6-d009f2ce0544.png)

**Comment by jdgarciauc3m** [comment]
We were able to reproduce the error.

Until we are able to solve it, please check using gcc.

**Comment by tete17** [comment]
I dont know the usual compiler the development team uses (i guess gcc 5 or 6) but we should consider raising a bug alert if it is able to compile, since the code is not following the standards, acording to this post https://stackoverflow.com/questions/14197436/c11-template-parameter-redefines-default-argument

**Comment by jdgarciauc3m** [comment]
Thank you very much for your contribution @tete17 .

Let us know your name and we will list you in the contributors list.

**Comment by tete17** [comment]
Miguel Sacristan Izcue

Thank you

**Comment by jdgarciauc3m** [comment]
Done!
Please, double check CREDITS.txt
