### ISSUE TITLE
Current map_reduce implementations not using identity_?

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#334]
We are not currently using `identity_` values in the following implementations:
- native
- omp
- tbb

We need to clarify if this is a design error or an implementation bug.

**Comment by jdgarciauc3m** [comment]
We have decided to review all parallel implementations to:
1. Make sure that identity is properly used.
2. The identity value is not used as initial value, but as identity value.

This issue partially addresses #290

**Comment by mdrocco** [comment]
I do not understand this choice. Which is the semantics of `map_reduce` for any value of the `identity` parameter? Is it non-deterministic for any value except the identity for the `combine_op ` function? If so, it sounds weird.

Why not treat it as an initial value, as in `std::reduce`?

**Comment by jdgarciauc3m** [comment]
Solved by #360
