### ISSUE TITLE
Reductions with defaulted identity value

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#343]
Add an additional family of reductions without identity value only for those types that are default constructible. That version assumes that the default value for the type is the identity value. Not that this is consistent with addition in numeric types.

This issue partiallly solves #290

**Comment by jdgarciauc3m** [comment]
@droccom has raised in comments at issue  #290 if we should provide reduce either with an identity value or an initial value. Rationale is being aligned with std::reduce

We need to discuss this in detail to make a decision.

**Comment by mdrocco** [comment]
If the target is strict consistency with `std::reduce`, there should be no way to both avoiding the initial value and using a custom binary operator (only `std::plus<>` is supported).

I think this case is very specific, so I suggest to either:
a. avoid adding it to the GrPPI API;
b. extend it to support generic binary operators (relaxing consistency with `std::reduce`)

**Comment by jdgarciauc3m** [comment]
New proposed resolution:

Do not take initial value or identity for reduction operations and apply the following semantics:
* reduce(ex, b, e, binop) -> if (distance(b,e) = 1)  return *b
* reduce(ex, b, e, binop) -> Apply reduction over range [b,e)
* reduce(ex, b, e, binop) -> if (distance(b,e) <1) return default constructed value

Requirements:
* value type must be default constructible
* The result is indeterminate if either binop is not associative or not commutative.

**Comment by mdrocco** [comment]
This solution makes great sense to me.

**Comment by jdgarciauc3m** [comment]
We keep the requirement of having to provide identity_value.

**Rationale**: This is in-line with new reduction objects of parallelism TS in C++. Fastflow also requires an identity value.
