### ISSUE TITLE
Make all sequential data patterns constexpr 

### ISSUE THREAD

**Issue by tete17** [arcosuc3m/grppi#350]
Would it be posible to make all sequential algorithms constexpr?

**Comment by jdgarciauc3m** [comment]
I doubt how useful this is in practice. 

However I am open to receiving pull requests for `constexpr` algorithms and analyze them. However each PR should contain changes for a single algorithms to make code reviews easier.

**Comment by jdgarciauc3m** [comment]
In last review we checked that map, reduce, map_reduce and stencil are already constexpr in the seq policy.

However, making the algorithmic interface constexpr would require more changes without any clear benefit.

We close this change as a rejection. 

Reopening should bring some motivating use case.
