### ISSUE TITLE
Stream Pool into Master branch

### ISSUE THREAD

**Issue by rossbory** [arcosuc3m/grppi#363]
Would be great to merge to Stream Pool pattern into the master branch and release it officially so we could use it in one of our projects.

**Comment by jdgarciauc3m** [comment]
The implementation is currently available in branch issue-363.

Before merging into Master we need to clarify which is the minimum openmp version that is needed.

On Travis OpenMP is freezing.

**Comment by jdgarciauc3m** [comment]
Solved by supporting only sequential and native.
