### ISSUE TITLE
Compile with C++20

### ISSUE THREAD

**Issue by Jerry-Ma** [arcosuc3m/grppi#371]
Hi,

It appears that the `meta::requires` function name is causing issues in compiling the code in c++20, in which `requires` is a keyword.

To fix that, an obvious approach is to rename `meta::requires` to `meta::requires_`.

**Comment by jdgarciauc3m** [comment]
This has been fixed with commit 1b5426e0ca8dd63b9b069efcfd0a8b0b03e10862
