### ISSUE TITLE
OMP and THR mode has poor performance

### ISSUE THREAD

**Issue by mjustyna32** [arcosuc3m/grppi#373]
Hello,

I am testing my application with omp and thr modes. Unfortunately, the perofromance of these modes is bad - they are always slower than seq mode. I also performed some test on different amount of cores on single node and on multiple nodes. The result is that it always uses only 1 core for computation. Can you help me solve this issue?
g++ version - 6.2
Compilation command:
g++-6.2 -O3 -pthread -DGRPPI_OMP -fopenmp -o main main.cpp
Running:
./main omp [files...]

Thanks!

**Comment by jdgarciauc3m** [comment]
Thanks!

Can you provide us with the example?

Either post it here or send it by email to josedaniel.garcia@uc3m.es

Thanks!

**Comment by mjustyna32** [comment]
Unfortunately, the program that I test is confidential and I cannot share it. In my use case I want to use map pattern, thus I tested provided examples to check if they have the same behaviour.
So when I run map or map-reduce examples add_sequences, double_sequence or word_count, I have exactly the same observations in htop - only 1 core is used with 100%, even though 16 cores are allocated for this job. 
Farm pattern, however, with omp mode uses all available cores.

**Comment by jdgarciauc3m** [comment]
When you are not able to provide confidential code, I hope you still can provide a simplified example. However, given your answer, the issue might be other.

Please, double check how many threads are seen by your execution policy.

You can get the concurrency degree of your execution policy by invoking:

```c++
int n = ex.concurrency_degree();
```

Please, note that if you are running in some environment your executable might get a wrong default.

With native policy the default is obtained by
```c++
std::thread::hardware_concurrency()
```

**Comment by mjustyna32** [comment]
I have tested proposed commands as suggested in the following form:
```
int thrs = std::thread::hardware_concurrency();
  cout<<"Hardware: "<<thrs<<endl;
  
  grppi::configuration<> config_{};
  int concurrency_degree_ = config_.concurrency_degree();
  
  cout<<"Grppi: "<<concurrency_degree_<<endl;
```
The result for both commands is 32.
This is the actual number of threads seen by system for whole node (Intel Xeon processor). I have allocated the resources with command:
```salloc -N1 -n8```

I have performed also other tests. For MAP pattern, omp utilize always 1 core. For FARM it utilizes maximum 6 cores, even if more are available.

**Comment by jdgarciauc3m** [comment]
Thanks!

For the map pattern what is the size of the sequence that you are processing?

For the farm, how many stages have your pipeline? How many stages are farmed? What is the cardinality?

**Comment by mjustyna32** [comment]
Hi,

for Map pattern I run samples built during installation e.g., add_sequences with command:
```
./add_sequences 99999999 omp
```
This size is big enough to observe CPU utilization in ```htop```

According to your question about  I have run all provided samples:
Sample: farm_pipeline utilizes all available CPUs. (run with command: ./sqrinv_seq_farm_pipe 9999999 omp), but the rest utilizes maximum 6 cores (capitalize and sqrinv_seq).

All in all, the most important for me is Map pattern working in parallel with openMP.

**Comment by jdgarciauc3m** [comment]
I'm closing this as new evaluations will be performed wit the new C++17 updated version.
