### ISSUE TITLE
Code for the paper "Supporting MPI-distributed stream parallel patterns in GrPPI"

### ISSUE THREAD

**Issue by ricardopieper** [arcosuc3m/grppi#374]
Hi guys,

I'm doing my masters degree dissertation at PUCRS - Brazil, and I'm citing GrPPI, specifically the paper that implements MPI https://dl.acm.org/doi/abs/10.1145/3236367.3236380. 

I'm wondering how you guys dealt with data serialization. I don't have the paper's PDF right now with me, so I don't remember if this was described there, but I think it wasn't. This is a very important detail I need to solve in my work (not fully automatic though) so I need to cite some works, and I found your paper months ago.

While I could just look at the code and figure out myself, I did not find the code for it. There is a branch called `distributed`, but i found no mention of MPI anywhere. Maybe I didn't look hard enough, so I'm asking for help. I'd like to take a look at the code and describe this work more accurately than I'm doing right now.

Can you guys give some directions?

**Comment by jdgarciauc3m** [comment]
Please, contact @javidoc00 for further details.

However, basically the serialization is handled by means of Boost.Serialize.
