### ISSUE TITLE
Polymorphic map - Support for several input arguments

### ISSUE THREAD

**Issue by AndresSanchezCuadrado** [arcosuc3m/grppi#48]
The polymorphic map does not support at the moment the use of the map patter with two or more input arguments.

For example, following code cannot be compiled:
grppi::map(e, begin(in), end(in), begin(out),
    [&](int i, int j) { return i*constant + j; }, begin(in2) );

Being in, out and in2 vectors of integers with the same length.

**Comment by jdgarciauc3m** [comment]
Created banch issue-48

**Comment by jdgarciauc3m** [comment]
This is pull request #68

**Comment by jdgarciauc3m** [comment]
Solved.
