### ISSUE TITLE
Remove enable_flags header

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#7]
Remove this file and the corresponding CMake machinery.

Users should compile with -DGRPPI_OMP or -DGRPPI_TBB and so

**Comment by Drioastorga** [comment]
I have removed that auto-generated file. In the current version to enable the different backends its only necessary to add the corresponding compiler flags:

"-DGRPPI_TBB": enables Intel TBB backend.
"-DGRPPI_OMP": enables OpenMP backend
"-DGRPPI_THRUST": enables Cuda Thrust backend.

I have also modified the CMake files to auto-detect the available frameworks in the system and introduce the corresponding compiler flags for the test aplications.

**Comment by jdgarciauc3m** [comment]
Done. However we probably need to revise documentation.
