### ISSUE TITLE
Algorithms and arity of functors

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#70]
Algorithms should check the arity of the operation functor. 

A simple compile error should be given, using a constraint (requires clause) or making use of a static_assert if the first option is problematic.

**Comment by jdgarciauc3m** [comment]
Constraining on functor arity cannot be done to support polymorphic lambdas.

Current partial solution is in branch check-arity.

We defer this issue for now, until we find a solution (possibly using concepts).

**Comment by tete17** [comment]
I do not understand the point of this ticket. If you try to usa a lambda with a different arity you will get a compile-time error anyway.
Is this only so that we control the error message?
Please clarify

**Comment by jdgarciauc3m** [comment]
That was the issue.

However we are closing this as we will approach the problem differently once we move to C++20 and concepts.
