### ISSUE TITLE
Enforce maximum warning levels from compiler

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#76]
We should have things like -Wall -Werror, ...

**Comment by tete17** [comment]
Should we also include `-Wextra` ?

**Comment by jdgarciauc3m** [comment]
Probably a complete list of this would be:

add_compile_options(-Wall -Wextra -Wno-deprecated -Werror -pedantic -pedantic-errors)

at least those should work on gcc and clang.
