### ISSUE TITLE
default_size should be a member constant

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#85]
`default_size` must be a member of class in file `mpmc_queue.h`.

There is no point in having a namespace constant that is only used in a class implementation.

**Comment by AndresSanchezCuadrado** [comment]
To do so, should we create the variable DEFAULT_SIZE as private and a getter function to retrieve the value?

**Comment by jdgarciauc3m** [comment]
NO!

The constant should be

~~~c++
constexpr static int default_size = 100;
~~~

**Comment by jdgarciauc3m** [comment]
We agree to remove the constant.

We will add a parameter to each exectuion info with the size (user modfiable) and make use of it when building queues.

**Comment by Drioastorga** [comment]
The default size constant has been removed. The default queue size is defined now in the execution models.

**Comment by jdgarciauc3m** [comment]
Solved by PR #139
