### ISSUE TITLE
Revise the design of execution model

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#9]
Is it really needed to have a class hierarchy?

**Comment by Drioastorga** [comment]
I reviewed the execution model class and I have removed it since it is not necessary anymore. I have also modified the signature of the pipeline function designed to be composed with other patterns. This way,  the heritage in the execution model classes is no longer required.

**Comment by jdgarciauc3m** [comment]
OK. Closed.
